sol = {
    'support': [[250., 400., 1], [250., 500., 1.5]],
    'hinder': [[450., 320., 1], [500., 320., 1.5]],
    'direction': [[240., 220., 1], [200., 340., 1.5]],
    'hole': [[250., 125., 1], [250., 175., 2.]],
    # 'multi_balls': [[(500., 400.), 1]],
    'stack': [],
    'fill': [],
    'multi_balls_spring_flick': [],
    'impulse_spring': [],
    'redirect': [],
    'lever': [],
    'seesaw': [],
    'angle': [],
    'impulse': [],
    'pendulum': [],
    'activated_pendulum': [],
    'spring_flick': [],
    'seesaw_angle': [],
    'noisy_support': [],
    'noisy_hinder': [],
    'noisy_direction': [],
    'noisy_hole': [],
    'noisy_fill': [],
    # 'noisy_lever': [],
    'noisy_seesaw': [],
    'noisy_angle': [],
    'noisy_impulse': [],
    'noisy_pendulum': [],
    'noisy_spring': [],
    'support_hinder': [],
    'support_direction': [],
    'support_hole': [],
    'more_step_hole': [],
    # 'multi_ball_support': [],
    'multi_ball_hinder': [],
    'multi_ball_hole': [],
    'multi_ball_fill': [],
    'multi_ball_angle': [],
    # 'multi_ball_support_joint': [],
    'multi_ball_pendulum': [],
    'multi_ball_spring': [],
    'impulse_pendulum': [],
    # 'multi_ball_support_spring': [],
    'spring': [],
    'hinder_fill': [],
}

if __name__ == '__main__':
    print(f'There are {len(sol)} games.')
    for key in sol.keys():
        print(key, end=' ')
