for game in support hinder direction hole multi_balls fill lever angle impulse pendulum activated_pendulum noisy_support noisy_hinder noisy_direction noisy_hole noisy_fill noisy_lever noisy_angle noisy_impulse support_hinder support_direction support_hole more_step_support more_step_hole more_ball_support more_ball_hole more_ball_support_joint impulse_joint more_ball_support_spring impulse_spring
do
  python ./run_game.py $game play
done