sol = {
            'support': [[(250., 400.), 1], [(250., 500.), 1.5]],
            'hinder': [[(450., 320.), 1], [(500., 320.), 1.5]],
            'direction': [[(240., 220.), 1], [(200., 340.), 1.5]],
            'hole': [[(250., 100.), 1], [(250., 150.), 2.]],
            'multi_balls': [[(500., 400.), 1]],
            'multi_balls_spring':[],
            'fill': [],
            'lever': [],
            'angle': [],
            'impulse': [],
            'pendulum': [],
            'spring_pendulum': [],
            'noisy_impulse': [],
            'noisy_support': [],
            'noisy_hinder': [],
            'noisy_direction': [],
            'noisy_hole': [],
            'noisy_fill': [],
            'noisy_lever': [],
            'noisy_angle': [],
            'support_hinder': [],
            'support_direction': [],
            'support_hole': [],
            'more_step_support': [],
            'more_step_hole': [],
            'more_ball_support': [],
            'more_ball_hole': [],
            'more_ball_support_joint': [],
            'impulse_joint': [],
            'more_ball_support_spring': [],
            'impulse_spring': [],
            'activated_pendulum': [],
        }
